// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddthttdwfpmjrgvkmwfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkdGh0dGR3ZnBtanJndmttd2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NDU0MzAsImV4cCI6MjA3MDQyMTQzMH0.-GMdNrEmGMhyjMIjLsIg5aBeyDdXwxVNWEa3GQcwjlw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});